---
title: "bridges_hmwk"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## R Markdown
```{r}
#Rhode Island Bridges 
#make a file with bridge ID, year, fips codes, condition ratings, and a few other variables.
code = read_delim(file = "https://www.fhwa.dot.gov/bridge/nbi/2019/delimited/RI19.txt", delim=",", col_names = T)

#Convert to date frame and cleans it up a little, 
#picking columns we want and renaming them for more clarity.
df = as.data.frame(code)
keep = c("STATE_CODE_001", "COUNTY_CODE_003", "FEATURES_DESC_006A", "YEAR_BUILT_027", 
         "TRAFFIC_LANES_ON_028A","DECK_COND_058", "SUPERSTRUCTURE_COND_059", "SUBSTRUCTURE_COND_060" )
df.update = df[keep]
names(df.update)[names(df.update) == "STATE_CODE_001"] <- "STATE_CODE"
names(df.update)[names(df.update) == "COUNTY_CODE_003"] <- "COUNTY_CODE"
names(df.update)[names(df.update) == "FEATURES_DESC_006A"] <- "FEATURES_DESC"
names(df.update)[names(df.update) == "YEAR_BUILT_027"] <- "YEAR_BUILT"
names(df.update)[names(df.update) == "TRAFFIC_LANES_ON_028A"] <- "#_TRAFFIC_LANES"
names(df.update)[names(df.update) == "STATE_CODE_001"] <- "STATE_CODE"
names(df.update)[names(df.update) == "DECK_COND_058"] <- "DECK_COND"
names(df.update)[names(df.update) == "SUPERSTRUCTURE_COND_059"] <- "SUP_STRUCTURE_COND"
names(df.update)[names(df.update) == "SUBSTRUCTURE_COND_060"] <- "SUB_STRUCTURE_COND"
head(df.update)
#lets plot some data looking at yeasr built and the substructure code 
#some bridges have "N" as a structure code and this is why NAs are produced when plotting. 
#Codes meaning: 9 - excellent, 8 - very good, 7 - good, 6 - satisfactory, 5- fair, 4 - poor, 
#3 - serious, 2 - critical, 1 - imminent failure, 0 - failed N - not applicable.
plot(df.update$YEAR_BUILT, df.update$SUB_STRUCTURE_COND, xlab = "Year Built", ylab = "Structure Safety Code")
#Interesting to see, we can see most bridges have a good rating, but there are some 3s. 
#It looks like a lot of bridges with acceptable ratings were made from 1950s to 2000s.
#However, it looks like half of the bridges that have poor scores of 3 were made during this time frame as well. 
```
